Drop DATABASE IF EXISTS bdOrangePoint;
CREATE DATABASE bdOrangePoint;
CREATE TABLE `bdOrangePoint`.`USUARIO` (
  `COD_USUARIO` INT NOT NULL AUTO_INCREMENT , 
  `LOGIN` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  `NME_FUNCIONARIO` VARCHAR(45) NULL,
  `HRS_DIARIA` DECIMAL(2,2) NULL,
  `FOTO_USUARIO` VARCHAR(100) NULL,
  PRIMARY KEY (`COD_USUARIO`));
  
  CREATE TABLE `bdOrangePoint`.`TIPO_PERMISSAO` (
  `COD_TIPO_PERMISSAO` INT NOT NULL AUTO_INCREMENT , 
  `DESC_PERMISSAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_TIPO_PERMISSAO`));
  
CREATE TABLE `bdOrangePoint`.`FOLHA_PONTO_USUARIO` (
  `COD_PONTO` INT NOT NULL AUTO_INCREMENT , 
  `COD_USUARIO` INT NOT NULL,
  `DATA_PONTO` DATE NOT NULL,
  `ENTRADA_1` VARCHAR(45) NULL,
  `SAIDA_1` VARCHAR(45) NULL,
  `ENTRADA_2` VARCHAR(45) NULL,
  `SAIDA_2` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_PONTO`),
  FOREIGN KEY(COD_USUARIO) REFERENCES bdOrangePoint.USUARIO (COD_USUARIO));
  
  CREATE TABLE `bdOrangePoint`.`PERMISSOES` (
  `COD_PERMISSAO` INT NOT NULL AUTO_INCREMENT , 
  `COD_USUARIO` INT NOT NULL,
  `COD_TIPO_PERMISSAO` INT NOT NULL,
  PRIMARY KEY (`COD_PERMISSAO`),
  FOREIGN KEY(COD_USUARIO) REFERENCES bdOrangePoint.USUARIO (COD_USUARIO),
  FOREIGN KEY(COD_TIPO_PERMISSAO) REFERENCES bdOrangePoint.TIPO_PERMISSAO (COD_TIPO_PERMISSAO));
  
  CREATE TABLE `bdOrangePoint`.`PERMISSOES_TELA` (
  `COD_PERMISSAO_TELA` INT NOT NULL AUTO_INCREMENT , 
  `COD_TIPO_PERMISSAO` INT NOT NULL,
  `DESCRICAO_TELA` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_PERMISSAO_TELA`),
  FOREIGN KEY(COD_TIPO_PERMISSAO) REFERENCES bdOrangePoint.TIPO_PERMISSAO (COD_TIPO_PERMISSAO));
  
   CREATE TABLE `bdOrangePoint`.`REGIME_EMPRESA` (
  `COD_REGIME` INT NOT NULL AUTO_INCREMENT , 
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_REGIME`));
  
  CREATE TABLE `bdOrangePoint`.`GRUPO_EMPRESA` (
  `COD_GRUPO` INT NOT NULL AUTO_INCREMENT , 
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_GRUPO`));
  
  CREATE TABLE `bdOrangePoint`.`TIPO_DATA` (
  `COD_TIPO_DATA` INT NOT NULL AUTO_INCREMENT , 
  `DESC_TIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_TIPO_DATA`));
  
  CREATE TABLE `bdOrangePoint`.`EMPRESA` (
  `COD_EMPRESA` INT NOT NULL AUTO_INCREMENT , 
  `COD_REGIME` INT NOT NULL,
  `COD_GRUPO` INT NOT NULL,
  `RAZAO_SOCIAL` VARCHAR(100) NOT NULL,
  `CNPJ` VARCHAR(45) NULL,
  `NUM_SOCIOS` INT NULL,
  `NUM_VINCULOS` INT NULL,
  `OBSERVACAO` VARCHAR(45),
  `SENHA_SIAT` VARCHAR(45),
  `ESOCIAL` VARCHAR(45),
  PRIMARY KEY (`COD_EMPRESA`),
  FOREIGN KEY(COD_REGIME) REFERENCES bdOrangePoint.REGIME_EMPRESA (COD_REGIME),
  FOREIGN KEY(COD_GRUPO) REFERENCES bdOrangePoint.GRUPO_EMPRESA (COD_GRUPO));
  
   CREATE TABLE `bdOrangePoint`.`DATAS_EMPRESA` (
  `COD_DATA` INT NOT NULL AUTO_INCREMENT , 
  `COD_TIPO_DATA` INT NOT NULL,
  `COD_EMPRESA` INT NOT NULL,
  `DATA` DATE NULL,
  PRIMARY KEY (`COD_DATA`),
  FOREIGN KEY(COD_TIPO_DATA) REFERENCES bdOrangePoint.TIPO_DATA (COD_TIPO_DATA),
  FOREIGN KEY(COD_EMPRESA) REFERENCES bdOrangePoint.EMPRESA (COD_EMPRESA));
  
  CREATE TABLE `bdOrangePoint`.`ALVARAS_EMPRESA` (
  `COD_ALVARA` INT NOT NULL AUTO_INCREMENT , 
  `COD_EMPRESA` INT NOT NULL,
  `DESC_ALVARA` INT NOT NULL,
  PRIMARY KEY (`COD_ALVARA`),
  FOREIGN KEY(COD_EMPRESA) REFERENCES bdOrangePoint.EMPRESA (COD_EMPRESA));
  
  CREATE TABLE `bdOrangePoint`.`DADOS_WEB_EMPRESA` (
  `COD_DADO_WEB` INT NOT NULL AUTO_INCREMENT , 
  `COD_EMPRESA` INT NOT NULL,
  `USUARIO_WEB` VARCHAR(45) NULL,
  `SENHA_WEB` VARCHAR(45) NULL,
  `DESC_DADO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_DADO_WEB`),
  FOREIGN KEY(COD_EMPRESA) REFERENCES bdOrangePoint.EMPRESA (COD_EMPRESA));
  
  CREATE TABLE `bdOrangePoint`.`CONTATOS_EMPRESA` (
  `COD_CONTATO` INT NOT NULL AUTO_INCREMENT , 
  `COD_EMPRESA` INT NOT NULL,
  `DESC_CONTATO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_CONTATO`),
  FOREIGN KEY(COD_EMPRESA) REFERENCES bdOrangePoint.EMPRESA (COD_EMPRESA));
  
  CREATE TABLE `bdOrangePoint`.`TIPO_CLASSIFICAO` (
  `COD_TIPO_CLASSIFICACAO` INT NOT NULL AUTO_INCREMENT , 
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_TIPO_CLASSIFICACAO`));
  
  CREATE TABLE `bdOrangePoint`.`CLASSIFICACAO_EMPRESA` (
  `COD_CLASSIFICACAO` INT NOT NULL AUTO_INCREMENT , 
  `COD_TIPO_CLASSIFICACAO` INT NOT NULL,
  `COD_DATA` INT NOT NULL,
  `FLAG_ATIVO` INT NOT NULL,
  PRIMARY KEY (`COD_CLASSIFICACAO`),
  FOREIGN KEY(COD_TIPO_CLASSIFICACAO) REFERENCES bdOrangePoint.TIPO_CLASSIFICAO (COD_TIPO_CLASSIFICACAO),
  FOREIGN KEY(COD_DATA) REFERENCES bdOrangePoint.DATAS_EMPRESA (COD_DATA));
  
  CREATE TABLE `bdOrangePoint`.`FUNCIONARIOS_EMPRESA` (
  `COD_FUNCIONARIO` INT NOT NULL AUTO_INCREMENT , 
  `COD_EMPRESA` INT NOT NULL,
  `NME_FUNCIONARIO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_FUNCIONARIO`),
  FOREIGN KEY(COD_EMPRESA) REFERENCES bdOrangePoint.EMPRESA (COD_EMPRESA));
  
  CREATE TABLE `bdOrangePoint`.`BENEFICIOS_FUNC` (
  `COD_BENEFICIO` INT NOT NULL AUTO_INCREMENT,
  `COD_FUNCIONARIO` INT NOT NULL, 
  `DESC_BENEFICIO` VARCHAR(45) NULL,
  `DATA_ACORDO` DATE NULL,
  `DATA_VENCIMENTO` DATE NULL,
  `FLG_PARC_FGTS` BOOLEAN NULL,
  PRIMARY KEY (`COD_BENEFICIO`),
  FOREIGN KEY(COD_FUNCIONARIO) REFERENCES bdOrangePoint.FUNCIONARIOS_EMPRESA (COD_FUNCIONARIO));
  
  CREATE TABLE `bdOrangePoint`.`TIPO_VALOR` (
  `COD_TIPO_VALOR` INT NOT NULL AUTO_INCREMENT, 
  `DESC_TIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_TIPO_VALOR`));
  
  CREATE TABLE `bdOrangePoint`.`SUBTIPO_VALOR` (
  `COD_SUBTIPO_VALOR` INT NOT NULL AUTO_INCREMENT, 
  `COD_TIPO_VALOR` INT NOT NULL, 
  `DESC_SUBTIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_SUBTIPO_VALOR`),
  FOREIGN KEY(COD_TIPO_VALOR) REFERENCES bdOrangePoint.TIPO_VALOR (COD_TIPO_VALOR));
  
  CREATE TABLE `bdOrangePoint`.`VALOR` (
  `COD_VALOR` INT NOT NULL AUTO_INCREMENT, 
  `COD_SUBTIPO_VALOR` INT NOT NULL, 
  `COD_DATA` INT NOT NULL,
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_VALOR`),
  FOREIGN KEY(COD_SUBTIPO_VALOR) REFERENCES bdOrangePoint.SUBTIPO_VALOR (COD_SUBTIPO_VALOR),
  FOREIGN KEY(COD_DATA) REFERENCES bdOrangePoint.DATAS_EMPRESA (COD_DATA));
  
  CREATE TABLE `bdOrangePoint`.`ATIVIDADE` (
  `COD_ATIVIDADE` INT NOT NULL AUTO_INCREMENT , 
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_ATIVIDADE`));
  
  CREATE TABLE `bdOrangePoint`.`SUBTIPO_ATIVIDADE` (
  `COD_SUBTIPO_ATIVIDADE` INT NOT NULL AUTO_INCREMENT, 
  `COD_ATIVIDADE` INT NOT NULL, 
  `COD_SUBTIPO_VALOR` INT NOT NULL,
  PRIMARY KEY (`COD_SUBTIPO_ATIVIDADE`),
  FOREIGN KEY(COD_ATIVIDADE) REFERENCES bdOrangePoint.ATIVIDADE (COD_ATIVIDADE),
  FOREIGN KEY(COD_SUBTIPO_VALOR) REFERENCES bdOrangePoint.SUBTIPO_VALOR (COD_SUBTIPO_VALOR));
  
  CREATE TABLE `bdOrangePoint`.`EMPRESA_ATIVIDADE` (
  `COD_EMPRESA_ATIVIDADE` INT NOT NULL AUTO_INCREMENT, 
  `COD_ATIVIDADE` INT NOT NULL, 
  `COD_EMPRESA` INT NOT NULL,
  PRIMARY KEY (`COD_EMPRESA_ATIVIDADE`),
  FOREIGN KEY(COD_ATIVIDADE) REFERENCES bdOrangePoint.ATIVIDADE (COD_ATIVIDADE),
  FOREIGN KEY(COD_EMPRESA) REFERENCES bdOrangePoint.EMPRESA (COD_EMPRESA));
  
  CREATE TABLE `bdOrangePoint`.`TIPO_BALANCO_PATRIMONIAL` (
  `COD_TIPO_BALANCO` INT NOT NULL AUTO_INCREMENT , 
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_TIPO_BALANCO`));
  
  CREATE TABLE `bdOrangePoint`.`SUBTIPO_BALANCO_PATRIMONIAL` (
  `COD_SUBTIPO_BALANCO` INT NOT NULL AUTO_INCREMENT, 
  `COD_TIPO_BALANCO` INT NOT NULL, 
  `DESC_SUBTIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_SUBTIPO_BALANCO`),
  FOREIGN KEY(COD_TIPO_BALANCO) REFERENCES bdOrangePoint.TIPO_BALANCO_PATRIMONIAL (COD_TIPO_BALANCO));
  
  CREATE TABLE `bdOrangePoint`.`VALOR_BALANCO_PATRIMONIAL` (
  `COD_VALOR_BALANCO` INT NOT NULL AUTO_INCREMENT, 
  `COD_SUBTIPO_BALANCO` INT NOT NULL, 
  `COD_VALOR` INT NOT NULL,
  PRIMARY KEY (`COD_VALOR_BALANCO`),
  FOREIGN KEY(COD_SUBTIPO_BALANCO) REFERENCES bdOrangePoint.SUBTIPO_BALANCO_PATRIMONIAL (COD_SUBTIPO_BALANCO),
  FOREIGN KEY(COD_VALOR) REFERENCES bdOrangePoint.VALOR (COD_VALOR));
  
  CREATE TABLE `bdOrangePoint`.`TIPO_LUCRO_REAL` (
  `COD_TIPO_LUCRO_REAL` INT NOT NULL AUTO_INCREMENT , 
  `DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_TIPO_LUCRO_REAL`));
  
  CREATE TABLE `bdOrangePoint`.`SUBTIPO_LUCRO_REAL` (
  `COD_SUBTIPO_LUCRO_REAL` INT NOT NULL AUTO_INCREMENT, 
  `COD_TIPO_LUCRO_REAL` INT NOT NULL, 
  `DESC_SUBTIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`COD_SUBTIPO_LUCRO_REAL`),
  FOREIGN KEY(COD_TIPO_LUCRO_REAL) REFERENCES bdOrangePoint.TIPO_LUCRO_REAL (COD_TIPO_LUCRO_REAL));
  
  CREATE TABLE `bdOrangePoint`.`VALOR_LUCRO_REAL` (
  `COD_VALOR_LUCRO_REAL` INT NOT NULL AUTO_INCREMENT, 
  `COD_SUBTIPO_LUCRO_REAL` INT NOT NULL, 
  `COD_VALOR` INT NOT NULL,
  PRIMARY KEY (`COD_VALOR_LUCRO_REAL`),
  FOREIGN KEY(COD_SUBTIPO_LUCRO_REAL) REFERENCES bdOrangePoint.SUBTIPO_LUCRO_REAL (COD_SUBTIPO_LUCRO_REAL),
  FOREIGN KEY(COD_VALOR) REFERENCES bdOrangePoint.VALOR (COD_VALOR));
  
ALTER TABLE bdorangepoint.folha_ponto_usuario
ADD OBSERVACAO VARCHAR(45);

INSERT INTO `bdorangepoint`.`usuario` (`LOGIN`, `SENHA`, `NME_FUNCIONARIO`) VALUES ('admin', 'administrador789654123', 'Administrador Geral');
INSERT INTO `bdorangepoint`.`tipo_permissao` (`DESC_PERMISSAO`) VALUES ('Administrador');
INSERT INTO `bdorangepoint`.`permissoes` (`COD_USUARIO`, `COD_TIPO_PERMISSAO`) VALUES ('1', '1');
INSERT INTO `bdorangepoint`.`permissoes_tela` (`COD_TIPO_PERMISSAO`, `DESCRICAO_TELA`) VALUES ('1', 'Cadastros');
INSERT INTO `bdorangepoint`.`permissoes_tela` (`COD_TIPO_PERMISSAO`, `DESCRICAO_TELA`) VALUES ('1', 'Consultoria Contábil');
INSERT INTO `bdorangepoint`.`permissoes_tela` (`COD_TIPO_PERMISSAO`, `DESCRICAO_TELA`) VALUES ('1', 'Apuração de Lucro Real');
INSERT INTO `bdorangepoint`.`permissoes_tela` (`COD_TIPO_PERMISSAO`, `DESCRICAO_TELA`) VALUES ('1', 'Controle de Usuários');
INSERT INTO `bdorangepoint`.`permissoes_tela` (`COD_TIPO_PERMISSAO`, `DESCRICAO_TELA`) VALUES ('1', 'Folha de Ponto');
INSERT INTO `bdorangepoint`.`permissoes_tela` (`COD_TIPO_PERMISSAO`, `DESCRICAO_TELA`) VALUES ('1', 'Controle de Folha de Ponto');
